stages:
  - deploy
  - resolve_deploy
 
deploy:
  stage: deploy
  only:
    - master
  before_script:
# add
  script:
    - echo "welcome1"
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd $WORK_DIR && git pull origin master && rm -rf build && npm run build && cp .htaccess build/"




  after_script:
#
  tags:
    - $TAGNAME


resolve_deploy:
  stage: resolve_deploy
  when: on_failure
  only:
    - master


  before_script:
# add next done
  script:
    - echo "resolve_deploy"
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd $WORK_DIR && git add . && git commit -m 'Automatically resolve merge conflict' && git pull origin master && rm -rf build && npm run build && cp .htaccess build/"


  # allow_failure: true  # Allow this stage to fail without affecting the pipeline status


  after_script:
# add 23
  tags:
    - $TAGNAME
