name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - master   # or master or whichever branch you want to trigger from

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl --request POST \
            --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            --form ref=master \
            https://git.devtechnosys.tech/api/v4/projects/778/trigger/pipeline
